# Generated by Django 6.0.1 on 2026-03-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_threatlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatlog',
            name='threat_type',
            field=models.CharField(choices=[('phishing', 'Phishing'), ('malware', 'Malware'), ('brute_force', 'Brute Force'), ('sql_injection', 'SQL Injection'), ('xss', 'XSS'), ('ransomware', 'Ransomware'), ('zero_day', 'Zero Day')], max_length=50),
        ),
    ]
