# Generated by Django 6.0.3 on 2026-03-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlog',
            name='full_answers',
            field=models.JSONField(default=dict),
        ),
    ]
