# Generated by Django 6.0.3 on 2026-03-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_quizlog_full_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='scan_type',
            field=models.CharField(choices=[('MALWARE', 'Malware Scan'), ('URL', 'URL Scan'), ('EMAIL', 'Email Scan'), ('SYSTEM', 'System Scan')], max_length=10),
        ),
    ]
