# Generated by Django 6.0.1 on 2026-01-28 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('FILE', 'File Scan'), ('URL', 'URL Scan'), ('SYSTEM', 'System Scan')], max_length=10)),
                ('target', models.CharField(max_length=500)),
                ('result', models.CharField(default='CLEAN', max_length=20)),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scan_time'],
            },
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('file_size', models.PositiveIntegerField()),
                ('threat_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('detection_details', models.JSONField(default=dict)),
                ('is_quarantined', models.BooleanField(default=False)),
                ('quarantine_path', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scan_date'],
            },
        ),
    ]
