# Generated by Django 6.0.1 on 2026-02-01 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_threatintelligence_threatlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threatlog',
            options={},
        ),
        migrations.RenameField(
            model_name='threatlog',
            old_name='detected_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='threatlog',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='threatlog',
            name='user',
        ),
        migrations.AddField(
            model_name='threatlog',
            name='file_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='target_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='detection_method',
            field=models.CharField(default='Manual', max_length=100),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='status',
            field=models.CharField(default='detected', max_length=20),
        ),
        migrations.AlterField(
            model_name='threatlog',
            name='threat_type',
            field=models.CharField(choices=[('phishing', 'Phishing'), ('malware', 'Malware'), ('ddos', 'DDoS'), ('brute_force', 'Brute Force'), ('sql_injection', 'SQL Injection'), ('xss', 'XSS'), ('ransomware', 'Ransomware'), ('zero_day', 'Zero Day')], max_length=50),
        ),
    ]
